const BADGES = [
  {id:'first_step',icon:'🌱',name:'Premier pas',desc:'Valider ton premier niveau.',test:s=>s.done>=1},
  {id:'five_levels',icon:'🔥',name:'En route',desc:'Valider 5 niveaux.',test:s=>s.done>=5},
  {id:'ten_levels',icon:'🚀',name:'Lancé',desc:'Valider 10 niveaux.',test:s=>s.done>=10},
  {id:'twenty_levels',icon:'💎',name:'Apprenti sérieux',desc:'Valider 20 niveaux.',test:s=>s.done>=20},
  {id:'first_course',icon:'🏁',name:'Parcours terminé',desc:'Terminer un parcours entier.',test:s=>s.finished>=1},
  {id:'java_master',icon:'☕',name:'Java solide',desc:'Terminer Java pour Paper.',test:s=>s.finishedId('java')},
  {id:'paper_builder',icon:'🧩',name:'Constructeur Paper',desc:'Terminer Créer un plugin Paper.',test:s=>s.finishedId('setup')},
  {id:'event_handler',icon:'⚡',name:'Maître des Events',desc:'Terminer Events.',test:s=>s.finishedId('events')},
  {id:'time_keeper',icon:'⏱️',name:'Maître du temps',desc:'Terminer Scheduler.',test:s=>s.finishedId('scheduler')},
  {id:'data_keeper',icon:'💾',name:'Gardien des données',desc:'Terminer Persistance & PDC.',test:s=>s.finishedId('data')},
  {id:'ui_creator',icon:'✨',name:'Créateur d’interfaces',desc:'Terminer UI & communication.',test:s=>s.finishedId('ui')},
  {id:'command_master',icon:'⌨️',name:'Architecte de commandes',desc:'Terminer Brigadier & commandes.',test:s=>s.finishedId('commands')},
  {id:'world_builder',icon:'🌍',name:'Maître du monde',desc:'Terminer Monde & entités.',test:s=>s.finishedId('world')},
  {id:'quality_guardian',icon:'🛡️',name:'Gardien de la qualité',desc:'Terminer Qualité & bonnes pratiques.',test:s=>s.finishedId('quality')},
  {id:'halfway',icon:'🌟',name:'À mi-chemin',desc:'Atteindre 50 % de la formation.',test:s=>s.total>0&&s.done/s.total>=.5},
  {id:'all_rounder',icon:'👑',name:'Paper Developer',desc:'Terminer tous les parcours disponibles.',test:s=>s.finished===s.totalCourses},
  {id:'completion',icon:'🏆',name:'Formation complète',desc:'Atteindre 100 % de la formation.',test:s=>s.total>0&&s.done===s.total}
];

function getBadgeStats(){const courses=Object.values(COURSES);const total=courses.reduce((n,c)=>n+c.levels.length,0);const done=Object.keys(progress.completed||{}).filter(k=>{const[a,b]=k.split(':');return !!COURSES[a]?.levels?.[Number(b)]}).length;const finished=courses.filter(c=>c.levels.every((_,i)=>!!progress.completed[`${c.id}:${i}`])).length;return{done,total,finished,totalCourses:courses.length,finishedId:id=>!!COURSES[id]&&COURSES[id].levels.every((_,i)=>!!progress.completed[`${id}:${i}`])}};
function earnedBadges(){const s=getBadgeStats();return BADGES.filter(b=>{try{return b.test(s)}catch{return false}})}
function renderProgressDashboard(){
 const root=document.getElementById('progressView');if(!root||root.classList.contains('hidden'))return;
 const s=getBadgeStats(),pct=s.total?Math.round(s.done/s.total*100):0,earned=earnedBadges(),ids=new Set(earned.map(b=>b.id));
 const rows=Object.values(COURSES).map(c=>{const d=c.levels.filter((_,i)=>!!progress.completed[`${c.id}:${i}`]).length,p=c.levels.length?Math.round(d/c.levels.length*100):0;return `<div class="dash-course"><div class="dash-course-icon">${c.icon}</div><div class="dash-course-info"><div class="dash-course-head"><strong>${escapeHtml(c.name)}</strong><span>${d}/${c.levels.length} · ${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div></div></div>`}).join('');
 const cards=BADGES.map(b=>`<article class="badge-card ${ids.has(b.id)?'earned':'locked'}"><div class="badge-icon">${ids.has(b.id)?b.icon:'🔒'}</div><div><strong>${escapeHtml(b.name)}</strong><p>${escapeHtml(b.desc)}</p></div><span class="badge-state">${ids.has(b.id)?'Débloqué':'À débloquer'}</span></article>`).join('');
 const history=(progress.history||[]).slice(0,8).map(x=>`<div class="activity-row"><span>✓ <strong>${escapeHtml(x.course)}</strong> — ${escapeHtml(x.title)}</span><time>${formatDate(x.at)}</time></div>`).join('');
 const next=BADGES.find(b=>!ids.has(b.id));
 root.innerHTML=`<section class="hero compact dashboard-hero"><span class="eyebrow">TABLEAU DE BORD</span><h1>Ta progression Paper.</h1><p>Chaque niveau validé fait avancer tes parcours et peut débloquer un badge.</p></section><section class="progress-hero card"><div class="progress-hero-main"><div><span class="eyebrow">PROGRESSION GLOBALE</span><div class="big-progress-number">${pct}%</div><p class="muted">${s.done} niveaux terminés sur ${s.total}</p></div><div class="progress-circle" style="--pct:${pct}%"><span>${pct}%</span></div></div><div class="progress"><i style="width:${pct}%"></i></div></section><section class="dashboard-stats"><div class="dash-stat card"><span class="dash-stat-icon">📚</span><div><small>Niveaux</small><strong>${s.done}/${s.total}</strong></div></div><div class="dash-stat card"><span class="dash-stat-icon">🏁</span><div><small>Parcours</small><strong>${s.finished}/${s.totalCourses}</strong></div></div><div class="dash-stat card"><span class="dash-stat-icon">🏅</span><div><small>Badges</small><strong>${earned.length}/${BADGES.length}</strong></div></div><div class="dash-stat card"><span class="dash-stat-icon">🎯</span><div><small>Objectif suivant</small><strong>${next?'À débloquer':'Terminé'}</strong></div></div></section><section class="dashboard-columns"><div class="card"><div class="section-head"><div><span class="eyebrow">COMPÉTENCES</span><h2>Progression par parcours</h2></div></div>${rows}</div><div class="card"><div class="section-head"><div><span class="eyebrow">OBJECTIF</span><h2>Prochain badge</h2></div></div><div class="next-badge"><span>${next?next.icon:'🏆'}</span><div><strong>${escapeHtml(next?next.name:'Collection complète')}</strong><p class="muted">${escapeHtml(next?next.desc:'Tous les badges sont débloqués !')}</p></div></div><div class="mini-progress"><div class="mini-progress-label"><span>Collection</span><span>${earned.length}/${BADGES.length}</span></div><div class="progress"><i style="width:${earned.length/BADGES.length*100}%"></i></div></div></div></section><section class="card badge-section"><div class="section-head"><div><span class="eyebrow">COLLECTION</span><h2>Badges</h2></div><span class="badge-count">${earned.length} débloqués</span></div><div class="badge-grid">${cards}</div></section><section class="card activity-section"><div class="section-head"><div><span class="eyebrow">ACTIVITÉ</span><h2>Dernières validations</h2></div></div>${history||'<p class="muted">Aucune validation pour le moment.</p>'}</section>`;
}
let badgeDashboardSignature='';setInterval(()=>{const v=document.getElementById('progressView');if(!v||v.classList.contains('hidden'))return;const s=getBadgeStats(),sig=`${s.done}|${s.finished}|${earnedBadges().map(b=>b.id).join(',')}`;if(sig!==badgeDashboardSignature){badgeDashboardSignature=sig;renderProgressDashboard();}},500);
