const COURSES = {
  html: {
    id:'html', name:'HTML', icon:'🌐', color:'Structure', description:'Construis la structure et le contenu sémantique de tes pages.',
    levels:[
      {title:'Niveau 1 — Première page',text:'HTML signifie HyperText Markup Language. Il décrit la structure d’un document avec des éléments comme h1, p, main et footer. Une page commence généralement par doctype, html, head et body.',code:'<!doctype html>\n<html lang="fr">\n<head>\n  <meta charset="utf-8">\n  <title>Ma page</title>\n</head>\n<body>\n  <h1>Bonjour !</h1>\n  <p>Ma première page web.</p>\n</body>\n</html>',tip:'Les balises décrivent le sens du contenu. Commence par une structure propre plutôt que par le design.',q:'Quelle balise contient le contenu visible de la page ?',a:['<head>','<body>','<meta>','<title>'],correct:1},
      {title:'Niveau 2 — Titres et texte',text:'Les titres vont de h1 à h6. Utilise p pour les paragraphes, strong pour une importance forte et em pour une emphase. La hiérarchie des titres aide la lisibilité et l’accessibilité.',code:'<h1>Mon blog</h1>\n<h2>Mon article</h2>\n<p>Un <strong>mot important</strong> et une <em>emphase</em>.</p>',tip:'Évite de choisir un titre uniquement parce qu’il est gros : choisis-le selon le niveau logique du document.',q:'Quel élément sert à représenter un paragraphe ?',a:['<text>','<paragraph>','<p>','<para>'],correct:2},
      {title:'Niveau 3 — Liens et navigation',text:'La balise a crée des liens. href indique la destination. Pour une navigation interne, tu peux utiliser un id comme cible. target="_blank" ouvre généralement un nouvel onglet.',code:'<nav>\n  <a href="/index.html">Accueil</a>\n  <a href="#contact">Contact</a>\n</nav>\n<section id="contact">Contact</section>',tip:'Un lien doit expliquer où il mène. Préfère « Voir le portfolio » à un vague « Cliquez ici ».',q:'Quel attribut contient la destination d’un lien ?',a:['src','href','action','target'],correct:1},
      {title:'Niveau 4 — Images et médias',text:'Les images utilisent img avec src et alt. alt décrit le contenu pertinent pour l’accessibilité et lorsque l’image ne peut pas être affichée. Les éléments audio et video peuvent intégrer des contrôles natifs.',code:'<img src="photo.jpg" alt="Un coucher de soleil sur la mer">\n<video controls src="intro.mp4"></video>',tip:'Une image décorative peut avoir un alt vide, tandis qu’une image informative doit avoir une description utile.',q:'Quel attribut est essentiel pour le texte alternatif d’une image ?',a:['href','alt','title','label'],correct:1},
      {title:'Niveau 5 — Listes et tableaux',text:'Utilise ul pour une liste non ordonnée, ol pour une liste ordonnée et li pour une entrée. Les tableaux utilisent table, thead, tbody, tr, th et td pour des données tabulaires.',code:'<ol>\n  <li>Apprendre HTML</li>\n  <li>Apprendre CSS</li>\n</ol>\n\n<table>\n  <thead><tr><th>Nom</th><th>Score</th></tr></thead>\n  <tbody><tr><td>Alice</td><td>95</td></tr></tbody>\n</table>',tip:'N’utilise pas un tableau pour faire de la mise en page. Un tableau sert à présenter des données liées.',q:'Quelle balise représente une ligne de tableau ?',a:['<td>','<tr>','<row>','<line>'],correct:1},
      {title:'Niveau 6 — Formulaires',text:'Les formulaires collectent des informations. label relie un texte à un champ grâce à for/id. Choisis le type d’input selon la donnée attendue.',code:'<form>\n  <label for="email">Email</label>\n  <input id="email" name="email" type="email" required>\n  <button type="submit">Envoyer</button>\n</form>',tip:'Des labels explicites rendent les formulaires plus accessibles et plus faciles à utiliser.',q:'Quel type d’input convient à une adresse email ?',a:['email','mailbox','address','contact'],correct:0},
      {title:'Niveau 7 — HTML sémantique',text:'Utilise header, nav, main, section, article, aside et footer pour exprimer la structure du document. La sémantique aide les navigateurs, moteurs de recherche et technologies d’assistance.',code:'<header>...</header>\n<nav>...</nav>\n<main>\n  <article>...</article>\n  <aside>...</aside>\n</main>\n<footer>...</footer>',tip:'Une div n’est pas mauvaise, mais une balise sémantique est souvent plus informative.',q:'Quelle balise devrait normalement contenir le contenu principal unique de la page ?',a:['<main>','<content>','<primary>','<section>'],correct:0},
      {title:'Niveau 8 — Accessibilité',text:'Une bonne page HTML doit rester utilisable au clavier et compréhensible avec une technologie d’assistance. Utilise des boutons pour les actions et des liens pour la navigation.',code:'<button type="button">Ouvrir</button>\n<a href="/profil">Voir le profil</a>\n<img src="logo.png" alt="WebCode Academy">',tip:'Ne transforme pas un div en bouton juste avec un clic JavaScript : utilise l’élément HTML adapté.',q:'Quel élément est le plus adapté pour déclencher une action ?',a:['<div>','<a>','<button>','<span>'],correct:2},
      {title:'Niveau 9 — SEO de base',text:'Le titre de la page, la description meta, une structure de titres cohérente et un contenu compréhensible améliorent la présentation et la découvrabilité.',code:'<head>\n  <meta name="description" content="Cours HTML pour débutants">\n  <title>Apprendre HTML</title>\n</head>',tip:'Le SEO ne se résume pas à des mots-clés : la qualité du contenu et sa structure comptent beaucoup.',q:'Quelle balise définit le titre affiché dans l’onglet du navigateur ?',a:['<h1>','<tab-title>','<title>','<name>'],correct:2},
      {title:'Niveau 10 — Projet HTML',text:'Mets tout ensemble : une page portfolio avec navigation, sections, image, liste de projets et formulaire de contact. L’objectif est de produire un HTML sémantique et accessible avant de passer au CSS.',code:'<main>\n  <section id="about">...</section>\n  <section id="projects">\n    <article>Projet 1</article>\n    <article>Projet 2</article>\n  </section>\n  <section id="contact">\n    <form>...</form>\n  </section>\n</main>',tip:'Avant de styliser, vérifie que la page reste logique même sans CSS.',q:'Quel est le meilleur ordre pour apprendre et construire cette page ?',a:['CSS puis structure HTML','Structure HTML puis CSS','JavaScript puis HTML','Images puis CSS'],correct:1}
    ]
  },
  css: {
    id:'css', name:'CSS', icon:'🎨', color:'Style', description:'Donne du style à tes pages et construis des interfaces responsive.',
    levels:[
      {title:'Niveau 1 — Sélecteurs et propriétés',text:'CSS associe un sélecteur à des déclarations. Un sélecteur de type cible des éléments, une classe se note avec . et un id avec #.',code:'p { color: blue; }\n.card { padding: 20px; }\n#hero { min-height: 400px; }',tip:'Les classes sont généralement le meilleur choix pour les styles réutilisables.',q:'Quel symbole commence un sélecteur de classe ?',a:['#','.',':','@'],correct:1},
      {title:'Niveau 2 — Couleurs, tailles et unités',text:'Tu peux utiliser des couleurs nommées, hexadécimales, rgb/rgba, etc. Pour les tailles, px, rem, em, %, vw et vh ont des usages différents.',code:'body {\n  color: #eef4ff;\n  font-size: 1rem;\n}\n.hero {\n  min-height: 80vh;\n}',tip:'rem est pratique pour des tailles liées à la taille de police racine ; les unités relatives sont importantes pour des interfaces adaptables.',q:'Quelle unité est relative à la taille de police de l’élément racine ?',a:['px','rem','vh','deg'],correct:1},
      {title:'Niveau 3 — Box model',text:'Chaque élément est une boîte : contenu, padding, border et margin. box-sizing:border-box rend le calcul des dimensions plus intuitif.',code:'* { box-sizing: border-box; }\n.card {\n  width: 320px;\n  padding: 20px;\n  border: 1px solid;\n  margin: 16px;\n}',tip:'Le padding est à l’intérieur de la boîte ; la margin crée de l’espace autour de la boîte.',q:'Quelle propriété ajoute de l’espace à l’intérieur d’un élément ?',a:['margin','padding','outline','gap'],correct:1},
      {title:'Niveau 4 — Cascade et spécificité',text:'Quand plusieurs règles ciblent le même élément, la cascade décide laquelle s’applique. La spécificité, l’ordre des règles et !important jouent un rôle.',code:'button { color: white; }\n.primary { color: yellow; }',tip:'Évite !important comme solution par défaut. Une architecture de classes claire réduit les conflits.',q:'Lequel est généralement plus spécifique : .primary ou button ?',a:['button','.primary','Ils sont identiques','Cela dépend de la police'],correct:1},
      {title:'Niveau 5 — Flexbox',text:'Flexbox est idéal pour aligner des éléments dans une dimension. display:flex active un conteneur flex. justify-content agit sur l’axe principal et align-items sur l’axe secondaire.',code:'.menu {\n  display: flex;\n  gap: 16px;\n  justify-content: space-between;\n  align-items: center;\n}',tip:'Commence par comprendre flex-direction, justify-content, align-items et gap.',q:'Quelle propriété contrôle l’alignement sur l’axe principal ?',a:['align-items','justify-content','align-content','place-items'],correct:1},
      {title:'Niveau 6 — Grid',text:'CSS Grid est très utile pour des layouts en deux dimensions : lignes et colonnes.',code:'.cards {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}',tip:'Grid est particulièrement pratique pour des grilles de cartes et des mises en page structurées.',q:'Quelle propriété définit les colonnes d’une grid ?',a:['grid-columns','grid-template-columns','columns-grid','template-columns'],correct:1},
      {title:'Niveau 7 — Positionnement',text:'position:relative crée un contexte utile pour positionner des descendants absolus. fixed reste attaché à la fenêtre dans les cas usuels, sticky mélange comportement relatif et fixation lors du défilement.',code:'.card { position: relative; }\n.badge {\n  position: absolute;\n  top: 12px;\n  right: 12px;\n}',tip:'Utilise le positionnement pour un besoin réel, pas pour faire toute la mise en page.',q:'Quelle position permet souvent de placer un badge dans un coin d’une carte ?',a:['static','absolute','inherit','float'],correct:1},
      {title:'Niveau 8 — Responsive design',text:'Une page responsive s’adapte aux largeurs d’écran. Les media queries permettent de changer des règles selon la taille ou d’autres caractéristiques.',code:'.layout { display: grid; grid-template-columns: 1fr 1fr; }\n@media (max-width: 700px) {\n  .layout { grid-template-columns: 1fr; }\n}',tip:'Construis d’abord un layout lisible sur petit écran, puis améliore les grands écrans si nécessaire.',q:'Quelle syntaxe permet d’appliquer des styles selon la largeur de l’écran ?',a:['@responsive','@media','@screen','@viewport'],correct:1},
      {title:'Niveau 9 — Transitions et états',text:'Les pseudo-classes comme :hover, :focus-visible et :disabled permettent de styliser des états. transition rend les changements plus fluides.',code:'button {\n  transition: transform .2s, opacity .2s;\n}\nbutton:hover { transform: translateY(-2px); }\nbutton:focus-visible { outline: 3px solid; }',tip:'Ne supprime jamais l’indicateur de focus sans fournir une alternative claire.',q:'Quelle pseudo-classe correspond à un élément recevant le focus clavier ?',a:[':click',':hover',':focus-visible',':keyboard'],correct:2},
      {title:'Niveau 10 — Projet CSS',text:'Stylise une page complète : variables CSS, layout avec Grid/Flexbox, cartes, navigation, états interactifs et responsive.',code:':root { --accent: #7f9cff; --radius: 18px; }\n.page { max-width: 1100px; margin: auto; padding: 24px; }\n.cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }\n@media (max-width: 800px) { .cards { grid-template-columns: 1fr; } }',tip:'Cherche une architecture de styles cohérente avant de multiplier les règles.',q:'Quel objectif principal doit avoir un design responsive ?',a:['Être identique sur tous les écrans','S’adapter aux tailles et contextes d’utilisation','Utiliser uniquement px','Supprimer les médias'],correct:1}
    ]
  },
  js: {
    id:'js', name:'JavaScript', icon:'⚙️', color:'Logique', description:'Ajoute du comportement, manipule le DOM et construis des applications interactives.',
    levels:[
      {title:'Niveau 1 — Variables et types',text:'Utilise const pour une liaison qui ne sera pas réassignée et let lorsqu’elle doit changer. Les types courants sont string, number, boolean, object et undefined.',code:'const name = "Alex";\nlet score = 0;\nscore += 10;\nconst active = true;',tip:'Privilégie const. Passe à let seulement quand la réassignation est nécessaire.',q:'Quelle déclaration convient à une valeur qui ne sera pas réassignée ?',a:['var','let','const','static'],correct:2},
      {title:'Niveau 2 — Conditions et opérateurs',text:'Les conditions permettent de décider. Utilise === et !== pour des comparaisons strictes dans la plupart des cas. && signifie ET, || signifie OU.',code:'if (score >= 100 && active) {\n  console.log("Bravo !");\n} else {\n  console.log("Continue !");\n}',tip:'Les conditions deviennent plus faciles à lire lorsqu’elles portent sur des variables bien nommées.',q:'Quel opérateur compare sans conversion implicite de type ?',a:['=','==','===','=>'],correct:2},
      {title:'Niveau 3 — Fonctions',text:'Une fonction regroupe du comportement réutilisable. Une fonction peut prendre des paramètres et retourner une valeur.',code:'function add(a, b) {\n  return a + b;\n}\n\nconst result = add(2, 3);',tip:'Une fonction claire fait idéalement une tâche identifiable et possède un nom explicite.',q:'Quel mot-clé renvoie une valeur depuis une fonction ?',a:['send','yield','return','output'],correct:2},
      {title:'Niveau 4 — Tableaux et objets',text:'Les tableaux stockent des collections ordonnées. Les objets regroupent des propriétés nommées.',code:'const users = [\n  { name: "Alice", score: 10 },\n  { name: "Bob", score: 20 }\n];\nconsole.log(users[0].name);',tip:'Apprends à combiner tableaux et objets : c’est très fréquent dans les applications web.',q:'Comment accéder au nom du premier utilisateur ?',a:['users.name','users[0].name','users.first.name','users(0).name'],correct:1},
      {title:'Niveau 5 — Méthodes de tableaux',text:'map transforme chaque élément, filter garde certains éléments, find retourne le premier élément correspondant et forEach exécute une action.',code:'const scores = [10, 20, 30];\nconst doubled = scores.map(score => score * 2);\nconst high = scores.filter(score => score >= 20);',tip:'Utilise la méthode qui décrit le mieux ton intention plutôt qu’une boucle manuelle systématique.',q:'Quelle méthode crée un nouveau tableau en transformant chaque élément ?',a:['filter','map','find','some'],correct:1},
      {title:'Niveau 6 — DOM',text:'Le DOM représente le document HTML. querySelector sélectionne selon un sélecteur CSS. textContent modifie le texte d’un élément.',code:'const title = document.querySelector("h1");\nif (title) {\n  title.textContent = "Nouveau titre";\n}',tip:'Teste les sélections qui peuvent ne rien trouver avant de manipuler l’élément.',q:'Quelle API sélectionne un élément avec un sélecteur CSS ?',a:['querySelector','findCSS','select','getNodeByCss'],correct:0},
      {title:'Niveau 7 — Événements',text:'Les événements permettent de réagir aux clics, saisies, touches et autres interactions. addEventListener associe un gestionnaire à un événement.',code:'const button = document.querySelector("button");\nbutton?.addEventListener("click", () => {\n  alert("Bonjour !");\n});',tip:'Sépare la détection de l’événement et la logique complexe en fonctions dédiées.',q:'Quelle méthode permet d’écouter un événement moderne ?',a:['onEvent()','addEventListener()','listen()','watch()'],correct:1},
      {title:'Niveau 8 — Asynchrone et fetch',text:'Le JavaScript navigateur est souvent asynchrone. fetch permet d’effectuer une requête HTTP et retourne une Promise.',code:'async function loadUsers() {\n  const response = await fetch("/users.json");\n  if (!response.ok) throw new Error("Erreur HTTP");\n  return response.json();\n}',tip:'Gère les erreurs réseau et HTTP. Un fetch terminé ne signifie pas forcément que le serveur a répondu avec un succès.',q:'Quel mot-clé permet d’attendre une Promise dans une fonction async ?',a:['pause','await','wait','yield'],correct:1},
      {title:'Niveau 9 — Modules et architecture',text:'Les modules ES permettent d’exporter et importer des fonctions ou constantes. Une architecture simple sépare données, logique et interface.',code:'// utils.js\nexport function formatScore(score) {\n  return `${score} pts`;\n}\n\n// app.js\nimport { formatScore } from "./utils.js";',tip:'Évite un fichier JavaScript géant : sépare les responsabilités.',q:'Quel mot-clé exporte une fonction d’un module ES ?',a:['share','export','public','module'],correct:1},
      {title:'Niveau 10 — Projet JavaScript',text:'Construis une petite application interactive : lecture de données, rendu dans le DOM, formulaire, événements, état local et gestion des erreurs.',code:'const state = { count: 0 };\n\nfunction render() {\n  document.querySelector("#count").textContent = String(state.count);\n}\n\ndocument.querySelector("#add")?.addEventListener("click", () => {\n  state.count += 1;\n  render();\n});\n\nrender();',tip:'Commence par un état simple, écris une fonction render et ajoute les interactions une par une.',q:'Quelle structure est la plus saine pour une petite interface interactive ?',a:['Tout dans un seul onclick HTML','État + fonctions + écouteurs d’événements','Uniquement des variables globales','Tout dans CSS'],correct:1}
    ]
  }
};
