const GUIDE_LIBRARY = [
  {category:'Java',level:'beginner',title:'Variables et types',description:'String, int, double, boolean et choix du bon type.',imports:['import java.util.UUID;']},
  {category:'Java',level:'beginner',title:'Conditions if / else',description:'Écrire une logique de décision claire dans un plugin.',imports:[]},
  {category:'Java',level:'beginner',title:'switch et switch expressions',description:'Choisir entre plusieurs états ou actions.',imports:[]},
  {category:'Java',level:'beginner',title:'Boucles for',description:'Parcourir des joueurs, items et collections.',imports:['import java.util.List;']},
  {category:'Java',level:'beginner',title:'Boucle for-each',description:'Parcourir proprement une collection Java.',imports:[]},
  {category:'Java',level:'beginner',title:'while et do-while',description:'Répéter une opération avec une condition.',imports:[]},
  {category:'Java',level:'beginner',title:'Méthodes',description:'Paramètres, valeurs de retour et visibilité.',imports:[]},
  {category:'Java',level:'beginner',title:'Constructeurs',description:'Initialiser correctement les objets de ton plugin.',imports:[]},
  {category:'Java',level:'beginner',title:'this et références',description:'Comprendre la référence vers l’instance courante.',imports:[]},
  {category:'Java',level:'beginner',title:'String et formatage',description:'Construire des textes propres pour le chat et les logs.',imports:[]},
  {category:'Java',level:'beginner',title:'Arrays',description:'Comprendre les tableaux avant de passer aux collections.',imports:[]},
  {category:'Java',level:'beginner',title:'null et NullPointerException',description:'Comprendre les références null et les vérifier.',imports:[]},
  {category:'Java',level:'intermediate',title:'List, Set et Map',description:'Choisir la bonne collection pour un plugin.',imports:['import java.util.List;','import java.util.Set;','import java.util.Map;']},
  {category:'Java',level:'intermediate',title:'HashMap et UUID joueur',description:'Associer des données aux joueurs connectés.',imports:['import java.util.HashMap;','import java.util.Map;','import java.util.UUID;']},
  {category:'Java',level:'intermediate',title:'computeIfAbsent',description:'Créer paresseusement les données joueur.',imports:['import java.util.Map;']},
  {category:'Java',level:'intermediate',title:'merge et compteurs',description:'Mettre à jour des compteurs élégamment.',imports:['import java.util.Map;']},
  {category:'Java',level:'intermediate',title:'Generics',description:'Écrire des structures de données typées.',imports:[]},
  {category:'Java',level:'intermediate',title:'Optional',description:'Utiliser Optional sans masquer des erreurs de conception.',imports:['import java.util.Optional;']},
  {category:'Java',level:'intermediate',title:'Enums pour les états',description:'WAITING, PLAYING, FINISHED et autres états métier.',imports:[]},
  {category:'Java',level:'intermediate',title:'Interfaces',description:'Créer des contrats réutilisables.',imports:[]},
  {category:'Java',level:'intermediate',title:'Records',description:'Modèles de données immuables modernes.',imports:[]},
  {category:'Java',level:'intermediate',title:'Immutabilité',description:'Réduire les effets de bord dans les services.',imports:[]},
  {category:'Java',level:'intermediate',title:'Exceptions checked / unchecked',description:'Choisir une stratégie d’erreur cohérente.',imports:[]},
  {category:'Java',level:'advanced',title:'Architecture orientée services',description:'Séparer logique métier et événements Paper.',imports:[]},
  {category:'Java',level:'advanced',title:'Dependency Injection manuelle',description:'Construire un graphe de dépendances simple sans framework.',imports:[]},
  {category:'Java',level:'advanced',title:'Concurrence Java',description:'Locks, collections concurrentes et problèmes de visibilité.',imports:['import java.util.concurrent.ConcurrentHashMap;']},
  {category:'Java',level:'advanced',title:'ExecutorService',description:'Gérer des tâches de fond côté Java.',imports:['import java.util.concurrent.ExecutorService;','import java.util.concurrent.Executors;']},
  {category:'Java',level:'advanced',title:'Tests unitaires des services',description:'Tester la logique métier indépendamment de Minecraft.',imports:[]},
  {category:'Java',level:'expert',title:'Conception modulaire d’un gros plugin',description:'Découper un plugin de plusieurs milliers de lignes.',imports:[]},
  {category:'Java',level:'expert',title:'API publique interne',description:'Exposer des interfaces stables à plusieurs modules.',imports:[]},
  {category:'Gradle & Maven',level:'beginner',title:'Créer un projet Gradle',description:'Structure src/main/java et premier build.',imports:[]},
  {category:'Gradle & Maven',level:'beginner',title:'Créer un projet Maven',description:'pom.xml, repository et première compilation.',imports:[]},
  {category:'Gradle & Maven',level:'beginner',title:'Comprendre les repositories',description:'Pourquoi Maven Central et le dépôt Paper existent.',imports:[]},
  {category:'Gradle & Maven',level:'beginner',title:'Configurer le JDK',description:'Choisir et déclarer une version Java cohérente.',imports:[]},
  {category:'Gradle & Maven',level:'intermediate',title:'compileOnly vs implementation',description:'Comprendre ce qui est fourni par le serveur.',imports:[]},
  {category:'Gradle & Maven',level:'intermediate',title:'Gestion des versions',description:'Éviter les dépendances incompatibles.',imports:[]},
  {category:'Gradle & Maven',level:'intermediate',title:'Resources du plugin',description:'Copier plugin.yml et fichiers de configuration dans le JAR.',imports:[]},
  {category:'Gradle & Maven',level:'advanced',title:'Shadow et shading',description:'Embarquer des bibliothèques dans le plugin.',imports:[]},
  {category:'Gradle & Maven',level:'advanced',title:'Relocation',description:'Éviter les conflits de packages entre plugins.',imports:[]},
  {category:'Gradle & Maven',level:'advanced',title:'Build CI avec GitHub Actions',description:'Compiler automatiquement un plugin à chaque push.',imports:[]},
  {category:'Gradle & Maven',level:'expert',title:'Projet multi-modules',description:'Séparer API, core, intégrations et outils.',imports:[]},
  {category:'Paper Core',level:'beginner',title:'Premier JavaPlugin',description:'Créer la classe principale et démarrer le plugin.',imports:['import org.bukkit.plugin.java.JavaPlugin;']},
  {category:'Paper Core',level:'beginner',title:'onEnable et onDisable',description:'Comprendre le cycle de vie.',imports:['import org.bukkit.plugin.java.JavaPlugin;']},
  {category:'Paper Core',level:'beginner',title:'plugin.yml',description:'Déclarer nom, version, main et api-version.',imports:[]},
  {category:'Paper Core',level:'beginner',title:'Accéder au serveur',description:'Bukkit, Server et PluginManager.',imports:['import org.bukkit.Bukkit;','import org.bukkit.Server;']},
  {category:'Paper Core',level:'beginner',title:'Logger du plugin',description:'Logs INFO, WARNING et SEVERE.',imports:['import java.util.logging.Level;']},
  {category:'Paper Core',level:'intermediate',title:'Enregistrement de composants',description:'Construire un démarrage propre.',imports:[]},
  {category:'Paper Core',level:'intermediate',title:'Injection des services',description:'Passer les dépendances par constructeur.',imports:[]},
  {category:'Paper Core',level:'intermediate',title:'Cycle de vie des ressources',description:'Créer, utiliser et fermer les ressources.',imports:[]},
  {category:'Paper Core',level:'advanced',title:'PluginManager et dépendances',description:'Gérer l’ordre de chargement et les dépendances.',imports:['import org.bukkit.plugin.PluginManager;']},
  {category:'Paper Core',level:'advanced',title:'Services optionnels',description:'Intégrer Vault ou une autre API sans rendre ton plugin inutilisable.',imports:[]},
  {category:'Paper Core',level:'expert',title:'Architecture de plateforme',description:'Construire une base partagée pour plusieurs plugins.',imports:[]},
  {category:'Events',level:'beginner',title:'Premier Listener',description:'Créer et enregistrer un listener.',imports:['import org.bukkit.event.EventHandler;','import org.bukkit.event.Listener;']},
  {category:'Events',level:'beginner',title:'PlayerJoinEvent',description:'Réagir à l’arrivée d’un joueur.',imports:['import org.bukkit.event.player.PlayerJoinEvent;']},
  {category:'Events',level:'beginner',title:'PlayerQuitEvent',description:'Nettoyer les données runtime à la déconnexion.',imports:['import org.bukkit.event.player.PlayerQuitEvent;']},
  {category:'Events',level:'beginner',title:'BlockBreakEvent',description:'Intercepter une casse de bloc.',imports:['import org.bukkit.event.block.BlockBreakEvent;']},
  {category:'Events',level:'beginner',title:'BlockPlaceEvent',description:'Contrôler la pose de blocs.',imports:['import org.bukkit.event.block.BlockPlaceEvent;']},
  {category:'Events',level:'beginner',title:'PlayerInteractEvent',description:'Détecter les interactions joueur.',imports:['import org.bukkit.event.player.PlayerInteractEvent;']},
  {category:'Events',level:'beginner',title:'InventoryClickEvent',description:'Réagir aux clics d’inventaire.',imports:['import org.bukkit.event.inventory.InventoryClickEvent;']},
  {category:'Events',level:'intermediate',title:'Cancellable',description:'Annuler proprement une action.',imports:['import org.bukkit.event.Cancellable;']},
  {category:'Events',level:'intermediate',title:'EventPriority',description:'Contrôler l’ordre de traitement.',imports:['import org.bukkit.event.EventPriority;']},
  {category:'Events',level:'intermediate',title:'Filtrage précoce',description:'Réduire le coût des events très fréquents.',imports:[]},
  {category:'Events',level:'intermediate',title:'Main hand / off hand',description:'Éviter de déclencher deux fois une action.',imports:['import org.bukkit.event.block.Action;']},
  {category:'Events',level:'advanced',title:'Listeners spécialisés',description:'Éviter les classes Event monolithiques.',imports:[]},
  {category:'Events',level:'advanced',title:'Event → Service',description:'Déléguer la logique métier à des services.',imports:[]},
  {category:'Events',level:'advanced',title:'Interactions entre plugins',description:'Comprendre les effets de priorité et d’annulation.',imports:[]},
  {category:'Events',level:'expert',title:'Système événementiel complexe',description:'Orchestrer plusieurs sous-systèmes sans effets de bord.',imports:[]},
  {category:'Scheduler',level:'beginner',title:'Comprendre les ticks',description:'20 TPS, 20 ticks et délais.',imports:[]},
  {category:'Scheduler',level:'beginner',title:'runTaskLater',description:'Exécuter une action après un délai.',imports:['import org.bukkit.Bukkit;']},
  {category:'Scheduler',level:'beginner',title:'runTaskTimer',description:'Créer une tâche répétée.',imports:['import org.bukkit.Bukkit;']},
  {category:'Scheduler',level:'beginner',title:'BukkitRunnable',description:'Créer une tâche avec état interne.',imports:['import org.bukkit.scheduler.BukkitRunnable;']},
  {category:'Scheduler',level:'intermediate',title:'Annuler une tâche',description:'Conserver BukkitTask et arrêter proprement.',imports:['import org.bukkit.scheduler.BukkitTask;']},
  {category:'Scheduler',level:'intermediate',title:'Cooldown par joueur',description:'Stocker les timestamps par UUID.',imports:['import java.util.HashMap;','import java.util.Map;','import java.util.UUID;']},
  {category:'Scheduler',level:'advanced',title:'Async et thread principal',description:'Séparer calcul/IO et API Paper.',imports:[]},
  {category:'Scheduler',level:'advanced',title:'File de travail',description:'Traiter progressivement de gros volumes.',imports:['import java.util.ArrayDeque;','import java.util.Queue;']},
  {category:'Scheduler',level:'expert',title:'Orchestrateur de tâches',description:'Ownership, annulation, quotas et observabilité.',imports:[]},
  {category:'Données',level:'beginner',title:'HashMap runtime',description:'Conserver une donnée temporaire en mémoire.',imports:['import java.util.HashMap;','import java.util.Map;']},
  {category:'Données',level:'beginner',title:'UUID comme clé',description:'Identifier les joueurs de façon stable.',imports:['import java.util.UUID;']},
  {category:'Données',level:'beginner',title:'PersistentDataContainer',description:'Stocker des identifiants techniques.',imports:['import org.bukkit.persistence.PersistentDataType;','import org.bukkit.NamespacedKey;']},
  {category:'Données',level:'beginner',title:'NamespacedKey',description:'Créer une clé PDC stable.',imports:['import org.bukkit.NamespacedKey;']},
  {category:'Données',level:'intermediate',title:'Metadata',description:'Gérer des états temporaires du runtime.',imports:['import org.bukkit.metadata.FixedMetadataValue;']},
  {category:'Données',level:'intermediate',title:'YAML avec FileConfiguration',description:'Lire et écrire de petites données.',imports:['import org.bukkit.configuration.file.FileConfiguration;']},
  {category:'Données',level:'intermediate',title:'Fichier YAML personnalisé',description:'Créer un DataManager dédié.',imports:['import org.bukkit.configuration.file.YamlConfiguration;']},
  {category:'Données',level:'intermediate',title:'Sauvegarde à la déconnexion',description:'Persist­er les données du joueur au bon moment.',imports:['import org.bukkit.event.player.PlayerQuitEvent;']},
  {category:'Données',level:'advanced',title:'SQLite',description:'Introduire une base locale structurée.',imports:['import java.sql.Connection;','import java.sql.PreparedStatement;','import java.sql.ResultSet;']},
  {category:'Données',level:'advanced',title:'MySQL',description:'Partager les données entre serveurs.',imports:['import java.sql.Connection;','import java.sql.PreparedStatement;']},
  {category:'Données',level:'advanced',title:'Repository Pattern',description:'Isoler l’accès aux données.',imports:[]},
  {category:'Données',level:'expert',title:'Migrations de schéma',description:'Faire évoluer une base en production.',imports:['import java.sql.Connection;','import java.sql.Statement;']},
  {category:'Données',level:'expert',title:'Cohérence et concurrence SQL',description:'Transactions, isolation et conflits d’écriture.',imports:['import java.sql.Connection;']},
  {category:'Configuration',level:'beginner',title:'config.yml',description:'Lire les paramètres du plugin.',imports:['import org.bukkit.configuration.file.FileConfiguration;']},
  {category:'Configuration',level:'beginner',title:'saveDefaultConfig',description:'Distribuer une configuration par défaut.',imports:['import org.bukkit.plugin.java.JavaPlugin;']},
  {category:'Configuration',level:'beginner',title:'Valeurs par défaut',description:'Éviter les réglages absents.',imports:[]},
  {category:'Configuration',level:'intermediate',title:'messages.yml',description:'Séparer textes et configuration.',imports:['import org.bukkit.configuration.file.YamlConfiguration;']},
  {category:'Configuration',level:'intermediate',title:'Configuration typée',description:'Transformer une config en objets métier.',imports:[]},
  {category:'Configuration',level:'advanced',title:'Reload propre',description:'Recharger sans casser les services actifs.',imports:[]},
  {category:'Configuration',level:'advanced',title:'Migration de configuration',description:'Conserver la compatibilité entre versions.',imports:[]},
  {category:'Items',level:'beginner',title:'Créer un ItemStack',description:'Créer ton premier item.',imports:['import org.bukkit.Material;','import org.bukkit.inventory.ItemStack;']},
  {category:'Items',level:'beginner',title:'ItemMeta',description:'Changer nom et apparence de l’item.',imports:['import org.bukkit.inventory.meta.ItemMeta;']},
  {category:'Items',level:'beginner',title:'DisplayName Adventure',description:'Donner un nom moderne à un item.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Items',level:'intermediate',title:'Lore',description:'Ajouter une description lisible.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Items',level:'intermediate',title:'PDC sur ItemMeta',description:'Identifier un item custom.',imports:['import org.bukkit.NamespacedKey;','import org.bukkit.persistence.PersistentDataType;']},
  {category:'Items',level:'intermediate',title:'ItemFactory',description:'Centraliser la création d’items.',imports:[]},
  {category:'Items',level:'intermediate',title:'Item flags',description:'Masquer certains détails visuels.',imports:['import org.bukkit.inventory.ItemFlag;']},
  {category:'Items',level:'advanced',title:'CustomModelData',description:'Relier l’item à un pack de ressources.',imports:[]},
  {category:'Items',level:'advanced',title:'Systèmes d’abilities',description:'Associer un item à une capacité métier.',imports:[]},
  {category:'Items',level:'expert',title:'Framework interne d’items',description:'Créer une API interne pour des centaines d’items.',imports:[]},
  {category:'Adventure & UI',level:'beginner',title:'Component.text',description:'Créer un message moderne.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Adventure & UI',level:'beginner',title:'Couleurs Adventure',description:'Colorer proprement les Components.',imports:['import net.kyori.adventure.text.format.NamedTextColor;']},
  {category:'Adventure & UI',level:'intermediate',title:'TextDecoration',description:'Gras, italique et autres décorations.',imports:['import net.kyori.adventure.text.format.TextDecoration;']},
  {category:'Adventure & UI',level:'intermediate',title:'MiniMessage',description:'Parser du texte configurable.',imports:['import net.kyori.adventure.text.minimessage.MiniMessage;']},
  {category:'Adventure & UI',level:'intermediate',title:'ActionBar',description:'Afficher un état court et dynamique.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Adventure & UI',level:'intermediate',title:'Titles',description:'Afficher un titre et un sous-titre.',imports:['import net.kyori.adventure.title.Title;','import net.kyori.adventure.text.Component;']},
  {category:'Adventure & UI',level:'intermediate',title:'Title.Times',description:'Régler les timings d’un Title.',imports:['import net.kyori.adventure.title.Title;','import java.time.Duration;']},
  {category:'Adventure & UI',level:'advanced',title:'BossBar',description:'Progression, timer et boss.',imports:['import net.kyori.adventure.bossbar.BossBar;']},
  {category:'Adventure & UI',level:'advanced',title:'Système de notifications',description:'Choisir entre chat, title, actionbar, son et toast.',imports:[]},
  {category:'Adventure & UI',level:'advanced',title:'Dialogues',description:'Concevoir une conversation et ses choix.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Adventure & UI',level:'expert',title:'UI orchestration',description:'Construire une expérience cohérente sur plusieurs canaux.',imports:[]},
  {category:'Joueurs',level:'beginner',title:'Récupérer un Player',description:'Obtenir le joueur depuis un event.',imports:['import org.bukkit.entity.Player;']},
  {category:'Joueurs',level:'beginner',title:'UUID du joueur',description:'Lire l’identifiant stable.',imports:['import java.util.UUID;']},
  {category:'Joueurs',level:'beginner',title:'Bukkit.getPlayer',description:'Trouver un joueur connecté par UUID.',imports:['import org.bukkit.Bukkit;','import org.bukkit.entity.Player;']},
  {category:'Joueurs',level:'beginner',title:'Tous les joueurs en ligne',description:'Parcourir la liste des joueurs.',imports:['import org.bukkit.Bukkit;','import org.bukkit.entity.Player;']},
  {category:'Joueurs',level:'intermediate',title:'Inventaire du joueur',description:'Ajouter et retirer des items.',imports:['import org.bukkit.inventory.PlayerInventory;']},
  {category:'Joueurs',level:'intermediate',title:'Permissions joueur',description:'Vérifier une capacité.',imports:['import org.bukkit.entity.Player;']},
  {category:'Joueurs',level:'intermediate',title:'Téléportation',description:'Déplacer un joueur vers une Location.',imports:['import org.bukkit.Location;','import org.bukkit.entity.Player;']},
  {category:'Joueurs',level:'advanced',title:'Cycle join → quit',description:'Créer un cycle de données joueur propre.',imports:[]},
  {category:'Joueurs',level:'advanced',title:'Gestion des joueurs hors ligne',description:'Séparer Player et données persistantes.',imports:['import org.bukkit.OfflinePlayer;']},
  {category:'Joueurs',level:'expert',title:'Player session manager',description:'Orchestrer sessions, cache et persistance.',imports:[]},
  {category:'Monde & Blocs',level:'beginner',title:'Location',description:'Comprendre coordonnées et monde.',imports:['import org.bukkit.Location;']},
  {category:'Monde & Blocs',level:'beginner',title:'Material',description:'Identifier le type d’un bloc ou item.',imports:['import org.bukkit.Material;']},
  {category:'Monde & Blocs',level:'beginner',title:'Block',description:'Lire et modifier un bloc.',imports:['import org.bukkit.block.Block;']},
  {category:'Monde & Blocs',level:'beginner',title:'Changer un bloc',description:'Utiliser setType.',imports:['import org.bukkit.Material;']},
  {category:'Monde & Blocs',level:'intermediate',title:'World',description:'Accéder à un monde et à ses entités.',imports:['import org.bukkit.World;']},
  {category:'Monde & Blocs',level:'intermediate',title:'getNearbyEntities',description:'Rechercher localement des entités.',imports:['import org.bukkit.entity.Entity;']},
  {category:'Monde & Blocs',level:'advanced',title:'Zones de gameplay',description:'Délimiter une région et ses règles.',imports:['import org.bukkit.Location;']},
  {category:'Monde & Blocs',level:'advanced',title:'Chunks et performances',description:'Comprendre le coût des accès monde.',imports:['import org.bukkit.Chunk;']},
  {category:'Monde & Blocs',level:'expert',title:'Édition massive du monde',description:'Concevoir une génération ou restauration efficace.',imports:[]},
  {category:'Entités',level:'beginner',title:'Entity',description:'Comprendre le type commun des entités.',imports:['import org.bukkit.entity.Entity;']},
  {category:'Entités',level:'beginner',title:'Spawn d’un Zombie',description:'Faire apparaître une créature.',imports:['import org.bukkit.World;','import org.bukkit.entity.Zombie;']},
  {category:'Entités',level:'beginner',title:'Nom custom d’une entité',description:'Afficher un nom visible.',imports:['import net.kyori.adventure.text.Component;']},
  {category:'Entités',level:'intermediate',title:'Glowing et effets visuels',description:'Améliorer la visibilité d’une entité.',imports:['import org.bukkit.entity.Entity;']},
  {category:'Entités',level:'intermediate',title:'Target et aggro',description:'Contrôler les interactions des mobs via l’API disponible.',imports:[]},
  {category:'Entités',level:'advanced',title:'Boss custom',description:'Assembler stats, UI, sons et récompenses.',imports:[]},
  {category:'Entités',level:'advanced',title:'Entity manager',description:'Gérer le cycle de vie des entités custom.',imports:['import org.bukkit.entity.Entity;']},
  {category:'Entités',level:'expert',title:'IA et NMS',description:'Aller plus loin que l’API Bukkit avec isolation.',imports:[]},
  {category:'Menus',level:'beginner',title:'Créer un inventaire GUI',description:'Première interface à slots.',imports:['import org.bukkit.Bukkit;','import org.bukkit.inventory.Inventory;']},
  {category:'Menus',level:'beginner',title:'Placer des boutons',description:'Construire une interface statique.',imports:['import org.bukkit.inventory.ItemStack;']},
  {category:'Menus',level:'intermediate',title:'InventoryClickEvent',description:'Intercepter les clics de GUI.',imports:['import org.bukkit.event.inventory.InventoryClickEvent;']},
  {category:'Menus',level:'intermediate',title:'Raw slot vs slot',description:'Comprendre la différence entre les deux coordonnées.',imports:['import org.bukkit.event.inventory.InventoryClickEvent;']},
  {category:'Menus',level:'intermediate',title:'Identifier un menu',description:'Ne pas dépendre uniquement du titre.',imports:[]},
  {category:'Menus',level:'advanced',title:'Interface Menu abstraite',description:'Construire un framework interne de menus.',imports:['import org.bukkit.inventory.Inventory;']},
  {category:'Menus',level:'advanced',title:'Pagination',description:'Naviguer entre plusieurs pages.',imports:[]},
  {category:'Menus',level:'expert',title:'Framework de GUI',description:'Créer un système de menus réutilisable.',imports:[]},
  {category:'Sons',level:'beginner',title:'playSound',description:'Jouer un son à un joueur.',imports:['import org.bukkit.Sound;']},
  {category:'Sons',level:'intermediate',title:'Pitch et volume',description:'Personnaliser le feedback sonore.',imports:['import org.bukkit.Sound;']},
  {category:'Sons',level:'advanced',title:'SoundService',description:'Centraliser les sons de l’application.',imports:['import org.bukkit.Sound;']},
  {category:'Sons',level:'expert',title:'Système audio de gameplay',description:'Créer une identité sonore cohérente.',imports:[]},
  {category:'Teams & Scoreboard',level:'beginner',title:'Créer une Team',description:'Ajouter un joueur à une équipe.',imports:['import org.bukkit.scoreboard.Team;']},
  {category:'Teams & Scoreboard',level:'beginner',title:'Couleur d’une Team',description:'Personnaliser l’affichage.',imports:['import org.bukkit.scoreboard.Team;']},
  {category:'Teams & Scoreboard',level:'intermediate',title:'Scoreboard sidebar',description:'Afficher des informations à droite de l’écran.',imports:['import org.bukkit.scoreboard.Scoreboard;','import org.bukkit.scoreboard.Objective;']},
  {category:'Teams & Scoreboard',level:'intermediate',title:'Objective',description:'Créer un objectif d’affichage.',imports:['import org.bukkit.scoreboard.Objective;']},
  {category:'Teams & Scoreboard',level:'advanced',title:'Scoreboard dynamique',description:'Mettre à jour efficacement un scoreboard.',imports:[]},
  {category:'Teams & Scoreboard',level:'advanced',title:'Isolation des scoreboards',description:'Éviter de modifier le scoreboard d’un autre plugin.',imports:[]},
  {category:'Teams & Scoreboard',level:'expert',title:'UI de scoreboard complexe',description:'Construire une couche d’affichage robuste.',imports:[]},
  {category:'Brigadier',level:'beginner',title:'Arbre de commande',description:'Comprendre littéraux et arguments.',imports:['import com.mojang.brigadier.builder.LiteralArgumentBuilder;']},
  {category:'Brigadier',level:'beginner',title:'LiteralArgumentBuilder',description:'Créer une racine et des sous-commandes.',imports:['import com.mojang.brigadier.builder.LiteralArgumentBuilder;']},
  {category:'Brigadier',level:'intermediate',title:'IntegerArgumentType',description:'Lire un entier validé.',imports:['import com.mojang.brigadier.arguments.IntegerArgumentType;']},
  {category:'Brigadier',level:'intermediate',title:'StringArgumentType',description:'Lire une chaîne utilisateur.',imports:['import com.mojang.brigadier.arguments.StringArgumentType;']},
  {category:'Brigadier',level:'intermediate',title:'Suggestions',description:'Compléter les joueurs ou valeurs.',imports:['import com.mojang.brigadier.suggestion.SuggestionProvider;']},
  {category:'Brigadier',level:'advanced',title:'Permissions sur les branches',description:'Protéger une sous-commande spécifique.',imports:[]},
  {category:'Brigadier',level:'advanced',title:'Commandes console-safe',description:'Gérer CommandSender et Player correctement.',imports:['import org.bukkit.command.CommandSender;','import org.bukkit.entity.Player;']},
  {category:'Brigadier',level:'expert',title:'DSL interne de commandes',description:'Simplifier la construction de dizaines de commandes.',imports:[]},
  {category:'Permissions',level:'beginner',title:'hasPermission',description:'Vérifier une permission.',imports:['import org.bukkit.entity.Player;']},
  {category:'Permissions',level:'beginner',title:'Noms de permissions',description:'Créer une convention stable.',imports:[]},
  {category:'Permissions',level:'intermediate',title:'Permissions de commandes',description:'Relier permissions et arbre de commande.',imports:[]},
  {category:'Permissions',level:'advanced',title:'Permissions contextuelles',description:'Rendre une capacité dépendante du contexte.',imports:[]},
  {category:'Permissions',level:'expert',title:'Intégration permission manager',description:'S’intégrer à un système externe proprement.',imports:[]},
  {category:'Performance',level:'beginner',title:'Pourquoi un plugin lag',description:'Comprendre CPU, IO et fréquence des tâches.',imports:[]},
  {category:'Performance',level:'beginner',title:'Éviter les scans inutiles',description:'Filtrer tôt et limiter les recherches.',imports:[]},
  {category:'Performance',level:'intermediate',title:'Optimiser une boucle de joueurs',description:'Réduire le travail par tick.',imports:['import org.bukkit.Bukkit;','import org.bukkit.entity.Player;']},
  {category:'Performance',level:'intermediate',title:'Optimiser une recherche d’entités',description:'Limiter distance et fréquence.',imports:['import org.bukkit.entity.Entity;']},
  {category:'Performance',level:'advanced',title:'Profiling',description:'Mesurer avant d’optimiser.',imports:[]},
  {category:'Performance',level:'advanced',title:'Travail réparti sur plusieurs ticks',description:'Éviter les gros pics de temps serveur.',imports:[]},
  {category:'Performance',level:'expert',title:'Architecture haute charge',description:'Concevoir pour un serveur très peuplé.',imports:[]},
  {category:'NMS',level:'advanced',title:'Quand utiliser NMS',description:'Identifier les cas où Paper ne suffit pas.',imports:[]},
  {category:'NMS',level:'advanced',title:'Isoler une API NMS',description:'Créer un adaptateur versionné.',imports:[]},
  {category:'NMS',level:'advanced',title:'Risques de compatibilité',description:'Comprendre les coûts des mises à jour.',imports:[]},
  {category:'NMS',level:'expert',title:'Adapter plusieurs versions',description:'Créer des implémentations par version.',imports:[]},
  {category:'NMS',level:'expert',title:'Internals Minecraft',description:'Explorer les mécaniques internes sans contaminer le code métier.',imports:[]},
  {category:'Tests',level:'beginner',title:'Tester une méthode Java',description:'Commencer les tests unitaires.',imports:[]},
  {category:'Tests',level:'intermediate',title:'Tester un service Paper',description:'Isoler la logique métier.',imports:[]},
  {category:'Tests',level:'advanced',title:'Mocker les dépendances',description:'Tester sans lancer tout le serveur.',imports:[]},
  {category:'Tests',level:'advanced',title:'Tests d’intégration',description:'Vérifier le comportement sur un environnement Paper.',imports:[]},
  {category:'Tests',level:'expert',title:'Stratégie de tests d’un gros plugin',description:'Unitaires, intégration, régression et CI.',imports:[]},
  {category:'Réseau & proxy',level:'intermediate',title:'Pourquoi utiliser un proxy',description:'Comprendre le besoin d’un réseau de serveurs.',imports:[]},
  {category:'Réseau & proxy',level:'advanced',title:'Communication inter-serveurs',description:'Échanger des données entre instances.',imports:[]},
  {category:'Réseau & proxy',level:'advanced',title:'Redis pour synchronisation',description:'Partager rapidement un état entre serveurs.',imports:[]},
  {category:'Réseau & proxy',level:'expert',title:'Architecture de network',description:'Concevoir une plateforme multi-serveurs.',imports:[]},
  {category:'Sécurité',level:'beginner',title:'Valider les entrées',description:'Ne jamais faire confiance aux arguments utilisateur.',imports:[]},
  {category:'Sécurité',level:'intermediate',title:'Éviter les abus de commandes',description:'Permissions, limites et cooldowns.',imports:[]},
  {category:'Sécurité',level:'advanced',title:'Sécurité des données SQL',description:'Requêtes préparées et validation.',imports:['import java.sql.PreparedStatement;']},
  {category:'Sécurité',level:'expert',title:'Threat model d’un plugin',description:'Identifier les surfaces d’attaque.',imports:[]},
  {category:'Publication',level:'beginner',title:'Build final',description:'Obtenir le JAR à distribuer.',imports:[]},
  {category:'Publication',level:'beginner',title:'README de plugin',description:'Documenter installation et configuration.',imports:[]},
  {category:'Publication',level:'intermediate',title:'Versioning sémantique',description:'Gérer proprement les versions.',imports:[]},
  {category:'Publication',level:'advanced',title:'Release automatisée',description:'Publier automatiquement depuis GitHub.',imports:[]},
  {category:'Publication',level:'expert',title:'Pipeline de publication professionnel',description:'Build, tests, artefacts, release et changelog.',imports:[]},
  {category:'Architecture',level:'intermediate',title:'Package structure',description:'Organiser command, listener, service et data.',imports:[]},
  {category:'Architecture',level:'intermediate',title:'Manager vs Service',description:'Savoir où placer une responsabilité.',imports:[]},
  {category:'Architecture',level:'advanced',title:'Domain model',description:'Faire porter les invariants par les bons objets.',imports:[]},
  {category:'Architecture',level:'advanced',title:'Ports and adapters',description:'Découpler le métier de Paper et SQL.',imports:[]},
  {category:'Architecture',level:'expert',title:'Clean Architecture pour Paper',description:'Construire un plugin testable et durable.',imports:[]},
  {category:'Architecture',level:'expert',title:'Plugin platform engineering',description:'Concevoir une base technique pour une équipe.',imports:[]}
];

window.GUIDE_LIBRARY = GUIDE_LIBRARY;
