const COURSES = {
  java: {
    id:'java', name:'Java pour Paper', icon:'☕', color:'Fondations', description:'Les bases Java dont tu as réellement besoin pour développer des plugins Paper.',
    levels:[
      {title:'Niveau 1 — Variables et types',text:'Apprends les variables, les chaînes, les nombres et les booléens. Ce sont les briques de toute logique de plugin.',code:'String name = "Steve";\nint coins = 100;\nboolean premium = false;',tip:'Commence par comprendre ce que contient chaque variable avant d’écrire de la logique complexe.',q:'Quel type représente un nombre entier en Java ?',a:['String','int','boolean','UUID'],correct:1},
      {title:'Niveau 2 — Méthodes',text:'Une méthode regroupe une action réutilisable. Elle peut recevoir des paramètres et retourner une valeur.',code:'public int addCoins(int coins, int amount) {\n    return coins + amount;\n}',tip:'Des méthodes courtes rendent tes services Paper beaucoup plus faciles à comprendre.',q:'Quel mot-clé renvoie une valeur depuis une méthode ?',a:['return','send','yield','output'],correct:0},
      {title:'Niveau 3 — Classes et objets',text:'Dans un plugin, crée des classes spécialisées pour éviter une énorme classe principale : PlayerData, CoinService, Menu, etc.',code:'public final class PlayerData {\n    private int coins;\n\n    public void addCoins(int amount) {\n        coins += amount;\n    }\n}',tip:'PlayerData est une classe de ton plugin : Paper ne la fournit pas.',q:'Qui crée une classe comme PlayerData ?',a:['Paper','Minecraft','Le développeur','Le serveur'],correct:2},
      {title:'Niveau 4 — Collections',text:'Map, List et Set sont omniprésentes dans les plugins. Utilise une Map quand tu veux associer une clé à une valeur.',code:'Map<UUID, Integer> coins = new HashMap<>();\ncoins.put(player.getUniqueId(), 100);',tip:'Une Map<UUID, ...> est souvent parfaite pour garder les données des joueurs connectés en mémoire.',q:'Quelle collection associe une clé à une valeur ?',a:['List','Map','Set','Queue'],correct:1},
      {title:'Niveau 5 — UUID',text:'Le nom d’un joueur peut changer. Son UUID est l’identifiant qu’il faut généralement utiliser pour les données persistantes.',code:'UUID uuid = player.getUniqueId();\nPlayerData data = players.get(uuid);',tip:'Ne construis pas un système de sauvegarde durable basé uniquement sur les pseudos.',q:'Quel identifiant est le meilleur choix pour des données joueur persistantes ?',a:['Le pseudo','L’UUID','La couleur','La position'],correct:1},
      {title:'Niveau 6 — Interfaces et enum',text:'Les interfaces définissent des contrats et les enums représentent un nombre limité d’états ou de valeurs.',code:'public enum GameState {\n    WAITING, PLAYING, FINISHED\n}\n\npublic interface RewardProvider {\n    void give(Player player);\n}',tip:'Les classes d’interface de ton projet sont aussi des classes personnalisées : tu dois les créer.',q:'Quel mot-clé permet de déclarer une liste de valeurs fixes ?',a:['enum','fixed','const','state'],correct:0},
      {title:'Niveau 7 — Exceptions et debug',text:'Apprends à lire les stacktraces et à traiter proprement les erreurs. Un plugin qui cache toutes les exceptions devient très difficile à maintenir.',code:'try {\n    loadData();\n} catch (IOException exception) {\n    getLogger().log(Level.SEVERE, "Chargement impossible", exception);\n}',tip:'N’utilise pas catch (Exception ignored) comme solution universelle.',q:'Pourquoi utiliser un logger avec l’exception ?',a:['Pour conserver le contexte de l’erreur','Pour créer un monde','Pour changer le TPS','Pour donner un item'],correct:0},
      {title:'Niveau 8 — Architecture Java',text:'Apprends à séparer modèle, service, repository et UI. Cette organisation sera réutilisée dans les chapitres suivants.',code:'Command / Event\n      ↓\n    Service\n      ↓\n Repository\n      ↓\n YAML / SQLite',tip:'Plus ton plugin grossit, plus la séparation des responsabilités devient importante.',q:'Où place-t-on idéalement la logique métier ?',a:['Dans un service','Dans config.yml','Dans Material','Dans le JAR'],correct:0}
    ]
  },
  setup: {
    id:'setup', name:'Créer un plugin Paper', icon:'🧩', color:'Projet', description:'De zéro à un plugin qui démarre proprement sur un serveur Paper.',
    levels:[
      {title:'Niveau 1 — Projet Gradle',text:'Configure un projet Gradle Java et ajoute paper-api comme dépendance de compilation.',code:'repositories {\n    mavenCentral()\n    maven("https://repo.papermc.io/repository/maven-public/")\n}\n\ndependencies {\n    compileOnly("io.papermc.paper:paper-api:VERSION")\n}',tip:'La version doit correspondre à celle de ton serveur cible.',q:'Quel type de dépendance utilise-t-on généralement pour paper-api ?',a:['compileOnly','implementation','testOnly','runtimeOnly'],correct:0},
      {title:'Niveau 2 — Classe principale',text:'La classe principale étend JavaPlugin. Elle est le point d’entrée géré par Paper.',code:'public final class MonPlugin extends JavaPlugin {\n    @Override\n    public void onEnable() {\n        getLogger().info("Activé !");\n    }\n}',tip:'MonPlugin est ta classe personnalisée. JavaPlugin est fournie par Paper.',q:'Quelle classe étend généralement la classe principale ?',a:['JavaPlugin','Player','World','PluginManager'],correct:0},
      {title:'Niveau 3 — Métadonnées',text:'Le fichier de métadonnées déclare le nom, la version et la classe principale du plugin.',code:'name: MonPlugin\nversion: "1.0.0"\nmain: fr.example.monplugin.MonPlugin\napi-version: "1.21"',tip:'Le champ main doit correspondre exactement au package et à la classe.',q:'Quel champ désigne la classe principale ?',a:['main','entry','start','class'],correct:0},
      {title:'Niveau 4 — onEnable',text:'Initialise ici tes services, ta configuration, tes listeners et tes commandes.',code:'@Override\npublic void onEnable() {\n    saveDefaultConfig();\n    // services\n    // listeners\n    // commandes\n}',tip:'La classe principale orchestre le démarrage ; elle ne doit pas contenir toute la logique.',q:'Quelle méthode correspond à l’activation du plugin ?',a:['onEnable','onStart','enablePlugin','loadAll'],correct:0},
      {title:'Niveau 5 — onDisable',text:'Sauvegarde et ferme les ressources lors de l’arrêt du plugin.',code:'@Override\npublic void onDisable() {\n    dataManager.saveAll();\n    database.close();\n}',tip:'dataManager et database seraient des classes personnalisées de ton plugin.',q:'Quel callback est destiné au nettoyage du plugin ?',a:['onDisable','onClose','shutdownPlugin','afterStop'],correct:0},
      {title:'Niveau 6 — Enregistrement des listeners',text:'Un listener doit être enregistré avec le PluginManager pour recevoir les événements.',code:'getServer().getPluginManager().registerEvents(\n    new PlayerListener(),\n    this\n);',tip:'PlayerListener est une classe que tu dois créer.',q:'Que fait registerEvents ?',a:['Enregistre un listener','Compile le plugin','Crée un monde','Sauvegarde YAML'],correct:0},
      {title:'Niveau 7 — Enregistrement des services',text:'Passe les dépendances aux classes personnalisées via leurs constructeurs plutôt que de créer partout des instances cachées.',code:'CoinService coinService = new CoinService(dataManager);\nPlayerListener listener = new PlayerListener(coinService);',tip:'CoinService, DataManager et PlayerListener sont des classes de ton plugin.',q:'Quel est l’intérêt principal de ce passage par constructeur ?',a:['Rendre les dépendances explicites','Accélérer le serveur','Créer un nouveau thread','Remplacer Paper'],correct:0},
      {title:'Niveau 8 — Premier build',text:'Compile le projet, récupère le JAR puis place-le dans plugins/ de ton serveur de développement.',code:'./gradlew build\n\n# puis\n# build/libs/MonPlugin-1.0.0.jar → server/plugins/',tip:'Teste toujours le JAR réellement produit plutôt que seulement ton code dans l’IDE.',q:'Où Gradle place-t-il généralement les JAR de build ?',a:['build/libs','target/plugins','dist/server','out/paper'],correct:0}
    ]
  },
  events:{
    id:'events', name:'Events', icon:'⚡', color:'Gameplay', description:'Réagis aux connexions, clics, dégâts, blocs, inventaires et autres actions du serveur.',
    levels:[
      {title:'Niveau 1 — Listener',text:'Un listener implémente Listener et contient des méthodes annotées @EventHandler.',code:'public final class JoinListener implements Listener {\n    @EventHandler\n    public void onJoin(PlayerJoinEvent event) {\n        // ...\n    }\n}',tip:'JoinListener est personnalisé ; Listener et PlayerJoinEvent viennent de Paper.',q:'Quelle annotation marque une méthode d’event ?',a:['@EventHandler','@Event','@Handle','@ListenerOnly'],correct:0},
      {title:'Niveau 2 — PlayerJoinEvent',text:'PlayerJoinEvent est déclenché lorsqu’un joueur rejoint le serveur.',code:'@EventHandler\npublic void onJoin(PlayerJoinEvent event) {\n    Player player = event.getPlayer();\n    player.sendMessage(Component.text("Bienvenue !"));\n}',tip:'Utilise getPlayer() quand l’event fournit le joueur.',q:'Comment récupère-t-on le joueur dans PlayerJoinEvent ?',a:['event.getPlayer()','event.player()','Bukkit.currentPlayer()','event.getSender()'],correct:0},
      {title:'Niveau 3 — Cancellable',text:'Certains événements peuvent être annulés. Après setCancelled(true), l’action est empêchée selon le comportement de l’event.',code:'@EventHandler\npublic void onBreak(BlockBreakEvent event) {\n    event.setCancelled(true);\n}',tip:'Tous les events ne sont pas annulables.',q:'Quelle méthode annule un event ?',a:['setCancelled(true)','cancelEvent()','deny()','stop()'],correct:0},
      {title:'Niveau 4 — EventPriority',text:'Quand plusieurs plugins écoutent le même event, EventPriority permet de contrôler l’ordre de traitement.',code:'@EventHandler(priority = EventPriority.HIGH)\npublic void onJoin(PlayerJoinEvent event) {\n    // ...\n}',tip:'MONITOR sert généralement à observer le résultat final et non à le modifier.',q:'Quelle priorité est destinée à observer le résultat final ?',a:['LOWEST','NORMAL','HIGH','MONITOR'],correct:3},
      {title:'Niveau 5 — PlayerInteractEvent',text:'Les événements d’interaction permettent de détecter les clics d’un joueur.',code:'@EventHandler\npublic void onInteract(PlayerInteractEvent event) {\n    if (event.getAction() == Action.RIGHT_CLICK_AIR) {\n        // clic droit\n    }\n}',tip:'Filtre tôt pour éviter d’exécuter de la logique inutile.',q:'Quel event est adapté à l’interaction d’un joueur ?',a:['PlayerInteractEvent','PlayerClickEvent','InteractPlayer','ClickActionEvent'],correct:0},
      {title:'Niveau 6 — InventoryClickEvent',text:'Cet event permet de contrôler les clics dans un inventaire et est très utilisé pour les menus custom.',code:'@EventHandler\npublic void onClick(InventoryClickEvent event) {\n    event.setCancelled(true);\n}',tip:'Pense aux clics dans la partie joueur et dans la partie supérieure du menu.',q:'Quel event est utilisé pour les clics d’inventaire ?',a:['InventoryClickEvent','InventoryUseEvent','MenuClickEvent','SlotClick'],correct:0},
      {title:'Niveau 7 — Event et service',text:'Le listener devrait détecter l’action puis déléguer la logique complexe à un service personnalisé.',code:'@EventHandler\npublic void onJoin(PlayerJoinEvent event) {\n    playerService.handleJoin(event.getPlayer());\n}',tip:'PlayerService est une classe personnalisée créée dans ton plugin.',q:'Pourquoi déléguer à PlayerService ?',a:['Séparer l’event de la logique métier','Créer un event','Changer le JAR','Éviter les imports'],correct:0},
      {title:'Niveau 8 — Projet Events',text:'Combine plusieurs listeners autour d’un service commun : connexion, clic, bloc et combat.',code:'PlayerListener\nBlockListener\nInventoryListener\n       ↓\nGameService',tip:'Les quatre classes sont des fichiers de ton projet, sauf les classes Paper utilisées par les méthodes.',q:'Quel découpage est le plus propre ?',a:['Plusieurs listeners → un service','Tout dans Main.java','Un plugin par event','Aucun listener'],correct:0}
    ]
  },
  scheduler:{
    id:'scheduler', name:'Scheduler', icon:'⏱️', color:'Temps', description:'Crée des tâches, timers, cooldowns et opérations asynchrones correctement.',
    levels:[
      {title:'Niveau 1 — Ticks',text:'Le serveur fonctionne par ticks. À 20 TPS, 20 ticks correspondent approximativement à une seconde.',code:'// environ 1 seconde\nrunTaskLater(plugin, task, 20L);',tip:'L est le suffixe Java pour un long.',q:'Combien de ticks correspondent environ à une seconde à 20 TPS ?',a:['2','10','20','200'],correct:2},
      {title:'Niveau 2 — runTaskLater',text:'Utilise runTaskLater pour exécuter une action une seule fois après un délai.',code:'Bukkit.getScheduler().runTaskLater(plugin, () -> {\n    player.sendMessage(Component.text("Plus tard"));\n}, 40L);',tip:'40 ticks représentent environ 2 secondes à 20 TPS.',q:'Que fait runTaskLater ?',a:['Exécute une fois après un délai','Répète chaque tick','Crée un event','Sauvegarde un item'],correct:0},
      {title:'Niveau 3 — runTaskTimer',text:'runTaskTimer répète une tâche avec une période donnée.',code:'Bukkit.getScheduler().runTaskTimer(\n    plugin,\n    () -> update(),\n    0L,\n    20L\n);',tip:'update serait une méthode de ta classe ou de ton service.',q:'Quel appel permet une tâche périodique ?',a:['runTaskTimer','runTaskLaterOnly','loopTask','repeatEvery'],correct:0},
      {title:'Niveau 4 — BukkitRunnable',text:'BukkitRunnable est une classe fournie par Bukkit et pratique quand la tâche possède son propre état.',code:'new BukkitRunnable() {\n    int remaining = 10;\n\n    @Override\n    public void run() {\n        remaining--;\n        if (remaining <= 0) cancel();\n    }\n}.runTaskTimer(plugin, 0L, 20L);',tip:'BukkitRunnable ne doit pas être redéfinie par ton plugin.',q:'Quelle méthode arrête la tâche depuis le Runnable ?',a:['cancel()','stop()','finish()','close()'],correct:0},
      {title:'Niveau 5 — Asynchrone',text:'Déporte certaines opérations lentes, comme une requête SQL indépendante, vers un thread asynchrone.',code:'Bukkit.getScheduler().runTaskAsynchronously(plugin, () -> {\n    repository.save(data);\n});',tip:'L’asynchrone n’autorise pas soudainement toutes les opérations Bukkit. Beaucoup d’API restent réservées au thread serveur.',q:'Quelle opération est un bon candidat à l’asynchrone ?',a:['Une requête SQL lente','Teleportation directe','Modification d’un bloc','Ouverture d’un inventaire'],correct:0},
      {title:'Niveau 6 — Revenir au thread serveur',text:'Après un traitement asynchrone, reviens sur le thread principal avant de manipuler des API qui l’exigent.',code:'runTaskAsynchronously(plugin, () -> {\n    Data data = repository.load(uuid);\n    runTask(plugin, () -> applyToPlayer(data));\n});',tip:'repository, Data et applyToPlayer peuvent être tes propres classes/méthodes.',q:'Pourquoi revenir au thread principal ?',a:['Pour les opérations Paper/Bukkit non thread-safe','Pour changer Java','Pour ouvrir GitHub','Pour accélérer Internet'],correct:0},
      {title:'Niveau 7 — Annuler un timer',text:'Conserve parfois le BukkitTask pour arrêter une tâche lorsqu’un système se termine.',code:'private BukkitTask task;\n\ntask = Bukkit.getScheduler().runTaskTimer(plugin, this::tick, 0L, 20L);\n\n// plus tard\ntask.cancel();',tip:'BukkitTask est fourni par Paper ; le champ task appartient à ta classe.',q:'Pourquoi conserver BukkitTask ?',a:['Pour pouvoir annuler la tâche','Pour créer un joueur','Pour sauvegarder YAML','Pour modifier un Material'],correct:0},
      {title:'Niveau 8 — Projet cooldown',text:'Construis un cooldown par joueur avec Map<UUID, Long>, une tâche périodique et un affichage ActionBar.',code:'Map<UUID, Long> cooldowns = new HashMap<>();\n\n// vérifier le temps restant\n// afficher l’état\n// supprimer les cooldowns terminés',tip:'La map est fournie par Java ; le gestionnaire de cooldown que tu écris est personnalisé.',q:'Quelle clé convient pour un cooldown joueur ?',a:['UUID','Material','Location uniquement','String de couleur'],correct:0}
    ]
  },
  data:{
    id:'data', name:'Persistance & PDC', icon:'💾', color:'Données', description:'Stocke des données en mémoire et de façon persistante avec PDC, YAML et bases de données.',
    levels:[
      {title:'Niveau 1 — HashMap en mémoire',text:'Une HashMap est idéale pour un cache ou des données temporaires associées à une clé.',code:'Map<UUID, PlayerData> players = new HashMap<>();\nplayers.put(uuid, data);',tip:'Une HashMap seule est perdue au redémarrage.',q:'Une HashMap est-elle persistante par elle-même ?',a:['Oui','Non','Uniquement avec JSON','Seulement sur Paper'],correct:1},
      {title:'Niveau 2 — PersistentDataContainer',text:'PDC permet de stocker des données sur des objets Paper compatibles, notamment des joueurs et des items.',code:'NamespacedKey key = new NamespacedKey(plugin, "coins");\nplayer.getPersistentDataContainer().set(\n    key, PersistentDataType.INTEGER, 100\n);',tip:'PDC est excellent pour de petites données liées directement à un objet.',q:'Quel système est adapté pour marquer un item custom ?',a:['PersistentDataContainer','Son lore seulement','Le nom du joueur','Le slot uniquement'],correct:0},
      {title:'Niveau 3 — NamespacedKey',text:'Une NamespacedKey donne un identifiant stable à ta donnée.',code:'NamespacedKey key = new NamespacedKey(plugin, "item_id");',tip:'Utilise des noms stables : les changements d’identifiant peuvent casser des données existantes.',q:'Quel objet identifie ta donnée dans le PDC ?',a:['NamespacedKey','UUID du serveur','Material','Scoreboard'],correct:0},
      {title:'Niveau 4 — Metadata',text:'La metadata convient aux informations temporaires pendant l’exécution, pas à une sauvegarde permanente.',code:'player.setMetadata(\n    "in-combat",\n    new FixedMetadataValue(plugin, true)\n);',tip:'Pour une donnée durable, utilise PDC ou un vrai système de stockage.',q:'Quel usage convient à Metadata ?',a:['État temporaire','Base de données permanente','Version du plugin','Configuration globale'],correct:0},
      {title:'Niveau 5 — YAML',text:'YAML est pratique pour la configuration et de petits volumes de données.',code:'config.set("players." + uuid + ".coins", 100);\nsaveConfig();',tip:'Pour beaucoup de joueurs, un fichier YAML unique peut devenir peu pratique.',q:'Quel format est utilisé par config.yml ?',a:['YAML','SQL','NBT uniquement','CSV obligatoire'],correct:0},
      {title:'Niveau 6 — PlayerData personnalisé',text:'Crée une classe PlayerData pour regrouper les données métier d’un joueur.',code:'public final class PlayerData {\n    private final UUID uuid;\n    private int coins;\n\n    public PlayerData(UUID uuid) { this.uuid = uuid; }\n}',tip:'PlayerData est une classe personnalisée de ton plugin.',q:'Pourquoi créer PlayerData ?',a:['Regrouper les données métier','Remplacer JavaPlugin','Modifier les blocs','Créer des events'],correct:0},
      {title:'Niveau 7 — Repository',text:'Un repository personnalisé isole la lecture et l’écriture du stockage.',code:'public final class PlayerDataRepository {\n    public PlayerData load(UUID uuid) {\n        return new PlayerData(uuid);\n    }\n\n    public void save(PlayerData data) { }\n}',tip:'PlayerDataRepository doit être créé par toi.',q:'Quel rôle joue un repository ?',a:['Isoler l’accès aux données','Créer des BossBars','Gérer les permissions','Gérer les clicks'],correct:0},
      {title:'Niveau 8 — Choisir le stockage',text:'Utilise HashMap pour le runtime, PDC pour des données attachées à des objets, YAML pour de petites données/configurations et SQL pour des volumes structurés.',code:'Runtime → HashMap\nObjet → PDC\nConfig → YAML\nGros volume → SQLite/MySQL',tip:'Il n’existe pas une seule solution parfaite : le choix dépend du volume et du cycle de vie.',q:'Quel choix est adapté à une grande quantité de données structurées ?',a:['Base SQL','Title','BossBar','Material'],correct:0}
    ]
  },
  items:{
    id:'items', name:'Items custom', icon:'🗡️', color:'Items', description:'Crée des objets personnalisés fiables et réagis à leurs interactions.',
    levels:[
      {title:'Niveau 1 — ItemStack',text:'ItemStack représente une pile d’items.',code:'ItemStack sword = new ItemStack(Material.DIAMOND_SWORD);',tip:'ItemStack est fourni par Bukkit/Paper.',q:'Quelle classe représente une pile d’items ?',a:['ItemStack','ItemData','StackItem','MinecraftStack'],correct:0},
      {title:'Niveau 2 — ItemMeta',text:'ItemMeta permet notamment de modifier le nom et le lore d’un item.',code:'ItemMeta meta = item.getItemMeta();\nmeta.displayName(Component.text("Épée magique"));\nitem.setItemMeta(meta);',tip:'Ne confonds pas texte visible et identité technique de l’item.',q:'Quelle classe permet de personnaliser les métadonnées visibles ?',a:['ItemMeta','ItemDisplay','MetaItem','ItemStyle'],correct:0},
      {title:'Niveau 3 — PDC sur un item',text:'Le PDC de l’ItemMeta permet d’ajouter un identifiant technique invisible.',code:'meta.getPersistentDataContainer().set(\n    key,\n    PersistentDataType.STRING,\n    "magic_sword"\n);',tip:'C’est préférable à une comparaison fragile du nom.',q:'Quelle donnée doit servir d’identifiant technique ?',a:['Le PDC','Le lore','La couleur','Le slot'],correct:0},
      {title:'Niveau 4 — Vérifier un item',text:'Lors d’un clic, vérifie null, matériau, meta et PDC avant d’exécuter une action.',code:'ItemStack item = event.getCurrentItem();\nif (item == null) return;\nItemMeta meta = item.getItemMeta();\nif (meta == null) return;',tip:'Les vérifications défensives évitent beaucoup d’erreurs.',q:'Pourquoi vérifier item == null ?',a:['Un slot peut ne contenir aucun item','Pour changer le matériau','Pour créer un joueur','Pour obtenir un UUID'],correct:0},
      {title:'Niveau 5 — Click dans un inventaire',text:'InventoryClickEvent est le point d’entrée classique pour un item bouton.',code:'@EventHandler\npublic void onClick(InventoryClickEvent event) {\n    event.setCancelled(true);\n}',tip:'Le listener qui contient cette méthode est une classe de ton plugin.',q:'Quel event est adapté au clic d’un item dans un inventaire ?',a:['InventoryClickEvent','ItemClickEvent','ButtonEvent','ClickItemEvent'],correct:0},
      {title:'Niveau 6 — ItemFactory',text:'Centralise la création de tous tes items custom dans une classe dédiée.',code:'public final class ItemFactory {\n    public ItemStack createMagicSword() {\n        return new ItemStack(Material.DIAMOND_SWORD);\n    }\n}',tip:'ItemFactory est une classe personnalisée : crée-la dans ton projet.',q:'Quel est l’avantage principal d’ItemFactory ?',a:['Centraliser les créations','Modifier Paper','Créer des threads','Sauvegarder SQL automatiquement'],correct:0},
      {title:'Niveau 7 — Items dans l’inventaire',text:'addItem peut retourner les items qui n’ont pas pu être placés, notamment lorsque l’inventaire est plein.',code:'Map<Integer, ItemStack> leftovers =\n    player.getInventory().addItem(item);',tip:'Traite les leftovers au lieu de perdre silencieusement les objets.',q:'Que peuvent contenir les leftovers ?',a:['Les items qui n’ont pas pu être ajoutés','Les joueurs hors ligne','Les blocs cassés','Les permissions'],correct:0},
      {title:'Niveau 8 — Projet item',text:'Construis une épée custom avec PDC, ItemFactory et un listener qui déclenche une capacité lors d’un clic.',code:'ItemFactory\n   ↓\nItemStack + PDC\n   ↓\nPlayerListener\n   ↓\nAbilityService',tip:'AbilityService est aussi une classe personnalisée à créer.',q:'Quel système identifie le mieux l’épée ?',a:['PDC','Nom visible uniquement','Slot fixe','Lore uniquement'],correct:0}
    ]
  },
  ui:{
    id:'ui', name:'UI & communication', icon:'✨', color:'Interface', description:'Maîtrise Adventure, chat, ActionBar, Titles, BossBars, sons, toasts et dialogues.',
    levels:[
      {title:'Niveau 1 — Component',text:'Adventure utilise Component pour représenter du texte riche et composable.',code:'player.sendMessage(\n    Component.text("Bienvenue !", NamedTextColor.GREEN)\n);',tip:'Component vient d’Adventure, utilisé par Paper moderne.',q:'Quelle classe représente un composant de texte ?',a:['Component','Message','Text','ChatComponentOnly'],correct:0},
      {title:'Niveau 2 — Append et styles',text:'Compose des messages avec append et applique des couleurs/décorations.',code:'Component message = Component.text("Bonjour ")\n    .append(Component.text(player.getName()))\n    .append(Component.text(" !"));',tip:'Le texte affiché et la logique du plugin restent séparés.',q:'Quelle méthode assemble deux Components ?',a:['append','join','merge','concatText'],correct:0},
      {title:'Niveau 3 — ActionBar',text:'L’ActionBar est parfaite pour une information courte et dynamique.',code:'player.sendActionBar(\n    Component.text("Cooldown : 5s")\n);',tip:'Évite de l’utiliser pour des paragraphes.',q:'Quel usage correspond à l’ActionBar ?',a:['État court','Long tutoriel','Stockage SQL','Menu permanent'],correct:0},
      {title:'Niveau 4 — Title',text:'Un Title s’affiche au centre et peut présenter un titre et un sous-titre.',code:'player.showTitle(Title.title(\n    Component.text("Victoire !"),\n    Component.text("Bravo !")\n));',tip:'Réserve les Titles aux événements importants.',q:'Où apparaît principalement un Title ?',a:['Au centre de l’écran','Dans le chat uniquement','Dans la hotbar','Dans la console'],correct:0},
      {title:'Niveau 5 — Timings',text:'Title.Times définit la durée d’apparition, de maintien puis de disparition.',code:'Title.Times times = Title.Times.times(\n    Duration.ofMillis(500),\n    Duration.ofSeconds(2),\n    Duration.ofMillis(500)\n);',tip:'Title.Times est fourni par Adventure.',q:'Que contrôle Title.Times ?',a:['Entrée, maintien et sortie','Jour, nuit et pluie','TPS et RAM','Vie du joueur'],correct:0},
      {title:'Niveau 6 — BossBar',text:'Une BossBar affiche un titre et une progression. Elle est utile pour un timer, un boss ou une capture.',code:'BossBar bar = Bukkit.createBossBar(\n    Component.text("Capture"),\n    BarColor.BLUE,\n    BarStyle.SOLID\n);\nbar.addPlayer(player);\nbar.progress(0.5);',tip:'Crée une BossBar une fois puis mets-la à jour.',q:'Quelle valeur représente 50 % ?',a:['0.5','50','1.5','2'],correct:0},
      {title:'Niveau 7 — Sons et toasts',text:'Les sons donnent un feedback immédiat. Les toasts sont des notifications liées au système d’advancements.',code:'player.playSound(\n    player.getLocation(),\n    Sound.ENTITY_PLAYER_LEVELUP,\n    1.0f, 1.0f\n);',tip:'Les toasts sont plus complexes à créer et dépendent de la version cible.',q:'Quel système Minecraft est lié aux toasts ?',a:['Advancements','Scoreboard','Teams','Recipes uniquement'],correct:0},
      {title:'Niveau 8 — Dialogues',text:'Les Dialogues modernes sont adaptés aux choix, confirmations et narrations. L’API exacte dépend de la version Paper ciblée.',code:'DialogueManager\n    ↓\nDialogue « Accepter / Refuser »\n    ↓\nQuestService.startQuest(player, "lost_sword");',tip:'DialogueManager et QuestService sont des classes de ton plugin. Vérifie toujours l’API publique de ta version avant d’utiliser du NMS.',q:'Pour quoi les Dialogues sont-ils particulièrement adaptés ?',a:['Choix et narration','Stockage des données','Modifier tous les blocs','Créer un JAR'],correct:0}
    ]
  },
  world:{
    id:'world', name:'Monde & entités', icon:'🌍', color:'Monde', description:'Manipule les joueurs, blocs, mondes, créatures et zones de gameplay.',
    levels:[
      {title:'Niveau 1 — Location',text:'Location regroupe un monde et des coordonnées.',code:'Location location = new Location(world, 0.5, 70, 0.5);',tip:'Les coordonnées sont des doubles.',q:'Quelle classe regroupe monde et coordonnées ?',a:['Location','Position','Coordinate','WorldPoint'],correct:0},
      {title:'Niveau 2 — Block et Material',text:'Block représente un bloc placé dans le monde. Material représente son type.',code:'Block block = location.getBlock();\nMaterial type = block.getType();\nblock.setType(Material.GOLD_BLOCK);',tip:'Block et Material sont fournis par Bukkit/Paper.',q:'Quelle méthode change le type d’un bloc ?',a:['setType','setMaterialId','changeTypeNow','applyMaterial'],correct:0},
      {title:'Niveau 3 — Player',text:'Player est le type utilisé pour manipuler un joueur connecté : message, inventaire, téléportation, permissions, etc.',code:'Player player = event.getPlayer();\nplayer.teleport(location);',tip:'Un Player peut devenir invalide si le contexte change : vérifie qu’il est encore connecté pour les tâches longues.',q:'Quelle classe représente un joueur connecté ?',a:['Player','User','MinecraftUser','OnlinePlayerData'],correct:0},
      {title:'Niveau 4 — Entity',text:'Entity est un type commun aux créatures et autres objets dynamiques.',code:'for (Entity entity : world.getEntities()) {\n    if (entity instanceof Zombie zombie) {\n        zombie.setGlowing(true);\n    }\n}',tip:'instanceof est une opération Java.',q:'Quel mot-clé teste le type d’un objet Java ?',a:['instanceof','typeof','isType','kindof'],correct:0},
      {title:'Niveau 5 — Spawn',text:'World peut faire apparaître une entité à une location.',code:'Zombie zombie = world.spawn(\n    location,\n    Zombie.class\n);',tip:'World et Zombie viennent de Paper/Bukkit.',q:'Quelle méthode fait apparaître une entité ?',a:['spawn','createMob','summonJava','spawnEntityOnly'],correct:0},
      {title:'Niveau 6 — Entité custom',text:'Tu peux personnaliser nom, visibilité, effets et comportements disponibles via l’API publique.',code:'zombie.customName(Component.text("Garde"));\nzombie.setCustomNameVisible(true);\nzombie.setGlowing(true);',tip:'Le nom visible est une propriété d’affichage, pas un identifiant technique.',q:'Quelle méthode rend le nom visible ?',a:['setCustomNameVisible(true)','showName()','enableNameTag()','visibleName()'],correct:0},
      {title:'Niveau 7 — Recherche locale',text:'Limite les recherches spatiales à une zone lorsque c’est possible.',code:'for (Entity entity : player.getNearbyEntities(10, 10, 10)) {\n    // ...\n}',tip:'Évite les scans de toutes les entités du serveur à chaque tick.',q:'Quel principe améliore une recherche d’entités ?',a:['Limiter la zone','Scanner tous les mondes','Scanner toutes les secondes sans filtre','Créer une boucle par mob'],correct:0},
      {title:'Niveau 8 — Projet zone',text:'Construis ZoneManager pour gérer une zone avec des blocs spéciaux, des mobs et des événements.',code:'public final class ZoneManager {\n    public void start(Location center) {\n        // initialiser la zone\n    }\n\n    public void stop() {\n        // nettoyer\n    }\n}',tip:'ZoneManager est entièrement une classe personnalisée de ton plugin.',q:'À quoi sert ZoneManager ?',a:['Centraliser la logique d’une zone','Remplacer World','Créer un JDK','Modifier config.yml automatiquement'],correct:0}
    ]
  },
  commands:{
    id:'commands', name:'Brigadier & commandes', icon:'⌨️', color:'Commandes', description:'Construis des commandes modernes, typées, suggérées et protégées par permission.',
    levels:[
      {title:'Niveau 1 — Arbre de commande',text:'Brigadier représente une commande avec des nœuds littéraux et des arguments.',code:'/coins give <joueur> <montant>\n\ncoins\n└─ give\n   ├─ joueur\n   └─ montant',tip:'Pense à tes commandes comme à un arbre.',q:'Comment Brigadier représente principalement une commande ?',a:['Un arbre','Une Map SQL','Une image','Un event unique'],correct:0},
      {title:'Niveau 2 — Littéral',text:'LiteralArgumentBuilder permet de construire les mots fixes de la commande.',code:'LiteralArgumentBuilder<CommandSourceStack> root =\n    LiteralArgumentBuilder.literal("coins");',tip:'LiteralArgumentBuilder vient de Brigadier.',q:'Que représente coins ?',a:['Un littéral','Un joueur','Un UUID','Une permission'],correct:0},
      {title:'Niveau 3 — Arguments',text:'RequiredArgumentBuilder construit un argument dynamique. IntegerArgumentType permet d’exiger un entier.',code:'RequiredArgumentBuilder<CommandSourceStack, Integer> amount =\n    RequiredArgumentBuilder.argument(\n        "amount",\n        IntegerArgumentType.integer(1, 64)\n    );',tip:'Les contraintes sont directement intégrées à l’argument.',q:'Que permet integer(1, 64) ?',a:['Entier de 1 à 64','String de 1 à 64','UUID','Nom de joueur'],correct:0},
      {title:'Niveau 4 — Lire un argument',text:'Récupère un argument depuis le contexte de la commande.',code:'int amount = IntegerArgumentType.getInteger(\n    context,\n    "amount"\n);',tip:'Le nom doit correspondre à l’argument déclaré.',q:'Comment récupère-t-on amount ?',a:['getInteger(context, "amount")','getArgumentOnly()','context.amount()','readAmount()'],correct:0},
      {title:'Niveau 5 — Suggestions',text:'Les suggestions proposent des valeurs pendant la saisie, par exemple les joueurs en ligne.',code:'suggests((context, builder) -> {\n    Bukkit.getOnlinePlayers().forEach(player ->\n        builder.suggest(player.getName())\n    );\n    return builder.buildFuture();\n});',tip:'Les suggestions doivent rester rapides.',q:'Que reçoit les valeurs suggérées ?',a:['Le builder','Le Player','Le Material','Le World'],correct:0},
      {title:'Niveau 6 — Permissions',text:'Utilise requires pour empêcher l’accès à une branche sans permission.',code:'.requires(source ->\n    source.getSender().hasPermission("monplugin.admin")\n)',tip:'Utilise une permission correspondant à une capacité précise.',q:'Que vérifie hasPermission ?',a:['La permission du sender','Son niveau Minecraft','Sa position','Son skin'],correct:0},
      {title:'Niveau 7 — Console et Player',text:'Une commande peut venir de la console. Vérifie la source avant de demander une API spécifique à Player.',code:'if (!(context.getSource().getSender() instanceof Player player)) {\n    return 0;\n}',tip:'Cela évite un cast invalide lorsque la console exécute la commande.',q:'Pourquoi utiliser instanceof Player ?',a:['Éviter un cast invalide','Créer un Player','Récupérer une permission automatiquement','Trouver un monde'],correct:0},
      {title:'Niveau 8 — Projet /coins',text:'Construis /coins, /coins balance et /coins give <joueur> <montant>, avec permissions et suggestions.',code:'/coins\n├─ balance\n└─ give <joueur> <montant>\n      ├─ suggestions joueurs\n      └─ permission give',tip:'MainCommand peut être une classe personnalisée du plugin.',q:'Quelle sous-commande nécessite typiquement une permission plus forte ?',a:['give','balance','coins uniquement','Aucune'],correct:0}
    ]
  },
  quality:{
    id:'quality', name:'Qualité & bonnes pratiques', icon:'🛡️', color:'Expert', description:'Construis des plugins fiables, performants et faciles à maintenir.',
    levels:[
      {title:'Niveau 1 — Permissions fines',text:'Prévois des permissions atomiques comme monplugin.command.reload ou monplugin.debug.',code:'monplugin.command.reload\nmonplugin.command.give\nmonplugin.debug',tip:'Évite de vérifier le pseudo d’un joueur pour décider s’il est administrateur.',q:'Quel système faut-il utiliser pour autoriser une action ?',a:['Permission','Pseudo en dur','Couleur du joueur','Nom du monde'],correct:0},
      {title:'Niveau 2 — Configuration propre',text:'Mets les valeurs modifiables par l’administrateur dans config.yml plutôt que de les coder partout.',code:'settings:\n  max-coins: 100000\n  welcome-enabled: true',tip:'Une configuration bien organisée évite de recompiler pour chaque petit réglage.',q:'Pourquoi utiliser config.yml ?',a:['Configurer le plugin sans modifier le code','Créer des joueurs','Remplacer Gradle','Créer des events'],correct:0},
      {title:'Niveau 3 — Messages séparés',text:'Un messages.yml peut contenir les textes et aider à traduire le plugin.',code:'messages:\n  welcome: "Bienvenue !"\n  no-permission: "Accès refusé."',tip:'Tu peux créer un MessageService personnalisé pour parser et envoyer ces textes.',q:'Quel avantage offre un fichier de messages ?',a:['Centraliser les textes','Modifier les chunks','Créer des threads','Compiler Java'],correct:0},
      {title:'Niveau 4 — Null et cas limites',text:'Un joueur peut être hors ligne, un item peut être absent ou une configuration peut manquer. Gère ces situations.',code:'Player player = Bukkit.getPlayer(uuid);\nif (player == null) {\n    return;\n}',tip:'Les vérifications de préconditions évitent beaucoup de NullPointerException.',q:'Pourquoi tester player == null ?',a:['Le joueur peut être hors ligne','Pour changer son nom','Pour créer un monde','Pour obtenir son skin'],correct:0},
      {title:'Niveau 5 — Performance',text:'Évite les scans globaux à chaque tick, les allocations inutiles et les opérations lourdes sur le thread principal.',code:'// Éviter :\n// tous les joueurs × toutes les entités × tous les blocs × chaque tick\n\n// Préférer : filtrer + limiter + planifier',tip:'20 ticks/s ne signifie pas que toutes les tâches doivent s’exécuter 20 fois par seconde.',q:'Quel principe est bon pour améliorer les performances ?',a:['Filtrer et réduire la fréquence','Tout scanner chaque tick','Créer plus de tâches','Ignorer le lag'],correct:0},
      {title:'Niveau 6 — NMS avec prudence',text:'Les classes internes net.minecraft.* sont plus fragiles entre versions. Préfère l’API Paper publique lorsque possible.',code:'API Paper\n   ↓\nsi nécessaire : adaptateur NMS\n   ↓\nreste du plugin indépendant',tip:'NmsAdapter est une classe personnalisée que tu peux créer pour isoler le code version-dépendant.',q:'Quelle approche facilite les mises à jour ?',a:['Isoler le NMS','Mettre du NMS partout','Copier un vieux tutoriel','Décompiler le serveur entier'],correct:0},
      {title:'Niveau 7 — Git',text:'Versionne ton plugin avec des commits clairs et fréquents.',code:'feat: add quest dialogue\nfix: prevent duplicate rewards\nrefactor: extract player service',tip:'Les commits sont une documentation du développement.',q:'Que signifie généralement fix ?',a:['Correction','Nouvelle fonctionnalité','Suppression du dépôt','Publication automatique'],correct:0},
      {title:'Niveau 8 — Checklist de publication',text:'Teste les données, permissions, tâches, commandes, menus, logs et compatibilité de la version ciblée avant de publier.',code:'✓ build propre\n✓ serveur de test\n✓ données persistantes\n✓ permissions\n✓ tâches nettoyées\n✓ aucun secret',tip:'Un plugin terminé est autant une question de fiabilité que de fonctionnalités.',q:'Quelle action est indispensable avant publication ?',a:['Tester le plugin sur un serveur de développement','Supprimer les logs','Modifier le JAR à la main','Retirer les permissions'],correct:0}
    ]
  }
};
